In [1]:
import numpy as np
import pandas as pd

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# Imputing with MICE
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

#Scaling the data
from sklearn.preprocessing import StandardScaler
from scipy import stats

# Model Evaluations
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import *
from imblearn.metrics import *

# plotting
import seaborn as sns
import matplotlib.pyplot as plt

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
from sklearn.feature_selection import RFECV

In [2]:
pd.set_option('display.max_columns',None)
#pd.set_option('display.max_row',None)

In [3]:
data = pd.read_csv("D:/SASTRA_AI_DS/MIni_project/Ovarian_Cancer_Diagnosis/Dataset/data_pre_meno.csv")

In [4]:
data

,AFP,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,BUN,Ca,CA125,CA19-9,CA72-4,CEA,CL,CO2CP,CREA,DBIL,EO#,EO%,GGT,GLO,GLU.,HCT,HE4,HGB,IBIL,K,LYM#,LYM%,MCH,MCV,Menopause,Mg,MONO#,MONO%,MPV,Na,NEU,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA,TYPE
0,3.58,19.36,47,45.4,56.0,11.0,24.0,0.01,0.30,5.35,2.48,15.36,36.48,6.42,1.40,107.4,19.9,103.0,2.0,0.04,1.00,16.0,28.5,4.67,0.273,NaN,89.0,3.5,5.36,0.65,16.8,33.7,103.4,0,0.78,0.22,5.70,11.70,141.3,76.2,0.090,13.4,1.46,74,2.64,13.7,5.5,73.9,396.4,0
1,1.50,18.40,39,45.4,77.0,9.0,18.0,0.03,0.60,3.80,2.57,56.08,12.18,NaN,0.77,102.6,22.2,48.0,4.7,0.03,0.60,10.0,32.5,4.64,0.391,47.56,131.0,10.1,4.30,1.10,23.7,28.4,84.6,0,1.00,0.25,5.40,11.40,138.9,69.7,0.130,15.2,0.97,112,4.62,12.0,14.8,77.9,209.2,0
2,2.36,19.97,45,35.0,47.0,21.0,27.0,0.01,0.10,4.89,2.48,1391.00,11.15,NaN,0.42,99.6,26.2,70.3,2.2,0.11,1.60,24.0,31.5,4.07,0.383,404.90,122.0,3.1,4.77,1.98,28.8,27.7,87.0,0,1.08,0.69,10.00,10.40,141.0,59.5,0.280,11.9,0.94,272,4.40,13.4,5.3,66.5,206.0,0
3,3.79,17.39,44,32.9,118.0,51.0,32.0,0.02,0.42,4.47,2.49,55.97,22.57,0.74,1.33,99.3,20.1,80.7,5.9,0.01,0.19,75.0,39.4,7.52,0.306,49.95,96.5,2.2,4.89,0.52,11.1,21.8,69.0,0,0.93,0.07,1.51,9.49,131.9,86.8,0.265,19.1,0.68,279,4.44,21.7,8.1,72.3,218.2,0
4,NaN,21.87,53,NaN,NaN,NaN,NaN,0.02,0.50,2.60,2.24,NaN,NaN,NaN,NaN,103.2,21.3,44.0,NaN,0.06,1.50,NaN,NaN,7.10,0.421,NaN,138.0,NaN,4.20,1.28,32.7,29.7,90.7,0,0.65,0.19,4.80,12.10,137.7,60.5,0.180,16.8,1.50,148,4.64,12.1,NaN,NaN,151.9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,3.27,21.32,43,48.6,60.0,30.0,16.0,0.03,0.50,4.86,2.58,13.61,8.37,NaN,0.59,96.5,24.6,67.0,2.9,0.06,1.10,29.0,25.8,4.39,0.440,40.17,147.0,4.8,4.12,1.36,24.3,30.4,91.1,0,0.94,0.21,3.80,10.90,138.3,NaN,0.230,13.2,1.07,210,4.83,12.1,7.7,74.4,379.0,1
226,2.09,20.91,52,48.6,65.0,40.0,30.0,0.00,0.00,4.29,2.81,50.80,15.11,NaN,1.74,98.1,25.9,54.0,3.8,0.01,0.30,36.0,31.8,5.13,0.415,31.45,142.0,6.9,4.11,1.18,30.7,31.1,91.0,0,0.94,0.28,7.30,9.90,140.8,NaN,0.220,10.8,0.99,219,4.56,11.9,10.7,80.4,241.5,1
227,2.00,12.14,37,46.1,49.0,9.0,20.0,0.00,0.00,3.12,2.29,21.93,0.62,NaN,1.67,103.6,25.0,67.0,5.9,0.02,0.30,9.0,27.4,4.59,0.285,44.44,80.0,11.3,3.64,1.39,23.3,18.9,67.2,0,0.77,0.32,5.40,11.90,137.1,NaN,0.310,17.3,0.95,262,4.24,17.7,17.2,73.5,240.5,1
228,1.84,27.22,30,47.8,64.0,26.0,22.0,0.03,0.30,3.61,2.82,53.87,10.71,NaN,0.93,93.1,23.1,59.0,3.5,0.23,2.20,25.0,28.2,5.59,0.458,30.78,154.0,7.8,4.22,2.15,20.6,28.8,85.6,0,1.02,0.43,4.10,10.50,139.2,NaN,0.420,13.4,1.31,398,5.35,12.5,11.3,76.0,285.7,1
229,1.61,13.00,39,44.9,68.0,7.0,13.0,0.01,0.20,4.38,2.58,46.45,28.79,NaN,0.76,101.7,29.5,69.0,2.7,0.04,0.80,8.0,23.7,4.94,0.376,33.42,128.0,5.6,4.30,1.52,32.0,31.0,91.0,0,0.93,0.30,6.30,10.30,139.9,NaN,0.230,11.0,1.10,224,4.13,12.1,8.3,68.6,184.9,1

In [5]:
data.isnull().sum()

AFP           13
AG             1
Age            0
ALB           10
ALP           10
ALT           10
AST           10
BASO#          0
BASO%          0
BUN            0
Ca             0
CA125         11
CA19-9        15
CA72-4       152
CEA           13
CL             0
CO2CP          1
CREA           0
DBIL          10
EO#            0
EO%            0
GGT           10
GLO           10
GLU.           0
HCT            0
HE4           12
HGB            0
IBIL          10
K              0
LYM#           0
LYM%           0
MCH            0
MCV            0
Menopause      0
Mg             0
MONO#          0
MONO%          0
MPV            2
Na             0
NEU           77
PCT            2
PDW            2
PHOS           0
PLT            0
RBC            0
RDW            0
TBIL          10
TP            10
UA             0
TYPE           0
dtype: int64

In [6]:
data['AFP'].mean()

16.260414746543777

In [8]:
data['AFP'].max()

1210.0

In [9]:
data['AFP'].fillna(value=6.47)

0      3.58
1      1.50
2      2.36
3      3.79
4      6.47
       ...
225    3.27
226    2.09
227    2.00
228    1.84
229    1.61
Name: AFP, Length: 230, dtype: float64

In [12]:
data['AFP'].describe()

count     217.000000
mean       16.260415
std       120.412242
min         0.610000
25%         1.500000
50%         2.200000
75%         3.470000
max      1210.000000
Name: AFP, dtype: float64

In [13]:
def remove_outliers_iqr(df):
    """
    Detect and truncate outliers using IQR method.
    Any value beyond 1.5 * IQR from the lower or upper quartile is considered an outlier
    and will be truncated to the respective bounds.
    """
    # Create a copy of the dataset
    df_outliers_removed = df.copy()

    for column in df_outliers_removed.select_dtypes(include=[np.number]):  # Process only numeric columns
        Q1 = df_outliers_removed[column].quantile(0.25)  # 25th percentile (lower quartile)
        Q3 = df_outliers_removed[column].quantile(0.75)  # 75th percentile (upper quartile)
        IQR = Q3 - Q1  # Inter-quartile range

        # Define the lower and upper bounds for outliers
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Truncate the outliers to the lower or upper bounds
        df_outliers_removed[column] = np.where(df_outliers_removed[column] < lower_bound, 
                                               lower_bound, 
                                               df_outliers_removed[column])
        df_outliers_removed[column] = np.where(df_outliers_removed[column] > upper_bound, 
                                               upper_bound, 
                                               df_outliers_removed[column])
    return df_outliers_removed

In [18]:
data = remove_outliers_iqr(data)

In [19]:
data['AFP'].describe()

count    217.000000
mean       2.642765
std        1.568141
min        0.610000
25%        1.500000
50%        2.200000
75%        3.470000
max        6.425000
Name: AFP, dtype: float64